Repository TTTReborn/tttreborn, pull requests merged in 2021-06, with the labels that each got.

#1 Update `ttt-reborn` into a working state
  .addon
  code/Game.cs
  code/Inventory.cs
  code/Karma.cs
  code/Properties/launchSettings.json
  code/items/Knife.cs
  code/player/Body.cs
  code/player/Player.Ammo.cs
  code/player/Player.cs
  code/player/camera/SpectateCamera.cs
  code/ttt-reborn.csproj
  code/ui/Crosshair.cs
  code/ui/Crosshair.scss
  code/ui/Hud.cs
  code/weapons/Knife.cs
  code/weapons/Pistol.cs
  code/weapons/SMG.cs
  code/weapons/Shotgun.cs
  code/weapons/ViewModel.cs
  code/weapons/Weapon.cs
  tools_thumbnail_cache.bin
Labels: enhancement

#5 Fix: Cmds and project cleanup
  .editorconfig
  .gitattributes
  .gitignore
  code/Game.ConVars.cs
  code/Game.cs
  code/Properties/launchSettings.json
  code/gamemode/Karma.cs
  code/player/Body.cs
  code/player/Player.Commands.cs
  code/player/Player.cs
  code/player/camera/SpectateCamera.cs
  code/tttreborn.csproj
  code/ui/Crosshair.cs
  code/ui/Crosshair.scss
  code/ui/Hud.cs
  code/ui/PlayerInfo.cs
  code/ui/PlayerInfo.scss
  code/weapons/Knife.cs
  code/weapons/Pistol.cs
  code/weapons/SMG.cs
  code/weapons/Shotgun.cs
  code/weapons/Weapon.cs
  omnisharp.json
Labels: bug

#3 Update `README.md` with discord information
  README.md
Labels: documentation

#7 RoundSystem: Added polymorphic round rework
  .gitignore
  code/Game.cs
  code/Properties/launchSettings.json
  code/rounds/BaseRound.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
  code/rounds/PreRound.cs
  code/rounds/WaitingRound.cs
  code/ttt-reborn.csproj
Labels: enhancement

#10 Meta: Removed ignored files
  code/Properties/launchSettings.json
  code/ttt-reborn.csproj
Labels: enhancement

#9 UI: Added PlayerInfo, GameTimer and WeaponSelection HUD elements
  code/Game.cs
  code/player/Player.cs
  code/ui/Crosshair.cs
  code/ui/GameTimer.cs
  code/ui/GameTimer.scss
  code/ui/Hud.cs
  code/ui/PlayerInfo.cs
  code/ui/PlayerInfo.scss
  code/ui/WeaponSelection.cs
  code/ui/WeaponSelection.scss
Labels: enhancement

#12 Fea: Hookup UI, assign roles, player bodies.
  code/Game.cs
  code/player/Body.cs
  code/player/Player.cs
  code/player/PlayerCorpse.cs
  code/player/camera/SpectateCamera.cs
  code/rounds/BaseRound.cs
  code/rounds/InProgressRound.cs
  code/rounds/PreRound.cs
  code/rounds/WaitingRound.cs
  code/ui/GameTimer.cs
  code/ui/Hud.cs
  code/ui/PlayerInfo.cs
  code/weapons/Weapon.cs
Labels: enhancement

#17 Input: Fix regarding latest changes
  code/player/camera/SpectateCamera.cs
  code/weapons/Pistol.cs
Labels: bug

#14 Fea: Inspecting bodies
  .gitignore
  code/player/Player.cs
  code/player/PlayerCorpse.cs
  code/rounds/InProgressRound.cs
  code/ui/Hud.cs
  code/ui/InfoFeed.cs
  code/ui/InfoFeed.scss
  code/ui/InfoFeedEntry.cs
  code/ui/InspectMenu.cs
  code/ui/InspectMenu.scss
  config/ttt-reborn.fgd
  tools_asset_info.bin
  ttt-reborn.fgd
Labels: enhancement

#15 Role System: Adding dynamic polymorphic role system
  code/player/Player.RPCs.cs
  code/player/Player.cs
  code/player/PlayerCorpse.cs
  code/roles/BaseRole.cs
  code/roles/InnocentRole.cs
  code/roles/NoneRole.cs
  code/roles/TraitorRole.cs
  code/rounds/InProgressRound.cs
  code/ui/PlayerInfo.cs
  config/tttreborn.fgd
Labels: enhancement

#18 [WIP] Hud: (by @Westsaid) Added scoreboard and working PlayerInfo
  assets/TTT-Reborn-Logo.png
  code/player/Player.Clothes.cs
  code/player/Player.RPCs.cs
  code/player/Player.cs
  code/ui/Crosshair.cs
  code/ui/GameTimer.cs
  code/ui/GameTimer.scss
  code/ui/Hud.cs
  code/ui/InfoFeed.cs
  code/ui/PlayerInfo.cs
  code/ui/PlayerInfo.scss
  code/ui/Scoreboard.cs
  code/ui/Scoreboard.scss
  code/ui/WeaponSelection.cs
  code/ui/WeaponSelection.scss
  code/weapons/Weapon.cs
Labels: enhancement

#16 Fea: Basic inventory mock
  code/gamemode/Inventory.cs
  code/player/Inventory.cs
  code/player/Player.cs
  code/rounds/InProgressRound.cs
  code/rounds/PreRound.cs
  code/ui/WeaponSelection.cs
  code/weapons/Knife.cs
  code/weapons/Pistol.cs
  code/weapons/SMG.cs
  code/weapons/Shotgun.cs
  code/weapons/Weapon.cs
  code/weapons/WeaponFunctions.cs
  config/tttreborn.fgd
Labels: enhancement

#19 Role System: Role syncing on player confirmation and PostRound start
  code/player/Player.RPCs.cs
  code/player/Player.cs
  code/rounds/PostRound.cs
  code/ui/InspectMenu.cs
Labels: enhancement

#21 Hud: Reworked InfoFeed hud element
  code/player/Player.RPCs.cs
  code/roles/BaseRole.cs
  code/roles/InnocentRole.cs
  code/roles/TraitorRole.cs
  code/ui/InfoFeed.cs
  code/ui/InfoFeed.scss
  code/ui/InfoFeedEntry.cs
  code/ui/PlayerInfo.scss
Labels: enhancement

#23 Fea: Show ammo reserve
  code/ui/PlayerInfo.cs
  code/ui/WeaponSelection.cs
  code/weapons/Pistol.cs
Labels: enhancement

#24 Bug: Fixed Prediction with RPCs (Net-Crash) and synced Role manually
  code/player/Player.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
Labels: bug

#25 HUD: InspectMenu rework
  code/player/Player.cs
  code/ui/InspectMenu.cs
  code/ui/InspectMenu.scss
Labels: enhancement

#29 Fea: Give players ammo, reintroduce crosshair
  code/rounds/InProgressRound.cs
  code/weapons/Weapon.cs
Labels: enhancement

#28 [WIP] Style adjustments (Inspect & overall)
  .gitignore
  code/roles/InnocentRole.cs
  code/roles/TraitorRole.cs
  code/ui/Crosshair.scss
  code/ui/GameTimer.cs
  code/ui/GameTimer.scss
  code/ui/InspectMenu.scss
  code/ui/PlayerInfo.cs
  code/ui/PlayerInfo.scss
  code/ui/Scoreboard.scss
  code/ui/WeaponSelection.scss
  tools_asset_info.bin
Labels: enhancement

#30 Bug: General fixes
  code/Game.Util.cs
  code/player/Player.RPCs.cs
  code/player/Player.cs
  code/player/camera/SpectateCamera.cs
  code/rounds/PostRound.cs
Labels: enhancement

#27 Scoreboard: Add groups (Dead)
  code/Game.Util.cs
  code/player/Player.RPCs.cs
  code/player/Player.cs
  code/ui/Hud.cs
  code/ui/Scoreboard.cs
  code/ui/Scoreboard.scss
  code/ui/ScoreboardEntry.cs
  code/ui/WeaponSelection.cs
Labels: enhancement

#31 Scoreboard: Added colored roles and auto confirmation in PostRound
  code/Game.cs
  code/player/Player.RPCs.cs
  code/player/Player.cs
  code/roles/BaseRole.cs
  code/roles/NoneRole.cs
  code/rounds/BaseRound.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
  code/ui/InfoFeed.cs
  code/ui/PlayerInfo.cs
  code/ui/PlayerInfo.scss
  code/ui/Scoreboard.cs
  code/ui/Scoreboard.scss
  code/ui/ScoreboardEntry.cs
Labels: area/UI, type/enhancement

#32 Added working Nameplates (one while looking on another player)
  code/ui/Hud.cs
  code/ui/Nameplate.cs
  code/ui/Nameplate.scss
Labels: area/UI, type/enhancement

#34 FEA: Post Round Menu
  code/player/Player.RPCs.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
  code/ui/Hud.cs
  code/ui/PostRoundMenu.cs
  code/ui/PostRoundMenu.scss
Labels: area/UI, area/code, type/enhancement

#35 Game: Adjusted damage, nameplate tracing and weapon switch shooting delay
  code/ui/Nameplate.cs
  code/weapons/Knife.cs
  code/weapons/Pistol.cs
  code/weapons/SMG.cs
  code/weapons/Shotgun.cs
  code/weapons/Weapon.cs
Labels: area/meta, type/enhancement

#26 Shop: Added functional QuickShop
  code/items/IBuyableItem.cs
  code/items/equipments/TTTEquipment.cs
  code/items/weapons/AmmoType.cs
  code/items/weapons/Knife.cs
  code/items/weapons/Pistol.cs
  code/items/weapons/SMG.cs
  code/items/weapons/Shotgun.cs
  code/items/weapons/TTTWeapon.cs
  code/items/weapons/ViewModel.cs
  code/items/weapons/WeaponFunctions.cs
  code/player/Inventory.cs
  code/player/TTTPlayer.Ammo.cs
  code/player/TTTPlayer.Clothes.cs
  code/player/TTTPlayer.Commands.cs
  code/player/TTTPlayer.Confirmation.cs
  code/player/TTTPlayer.RPCs.cs
  code/player/TTTPlayer.Shop.cs
  code/player/TTTPlayer.cs
  code/rounds/InProgressRound.cs
  code/rounds/PreRound.cs
  code/ui/Crosshair.cs
  code/ui/Hud.cs
  code/ui/InfoFeed.cs
  code/ui/InspectMenu.cs
  code/ui/InspectMenu.scss
  code/ui/PlayerInfo.cs
  code/ui/PostRoundMenu.cs
  code/ui/QuickShop.cs
  code/ui/QuickShop.scss
  code/ui/WeaponSelection.cs
Labels: area/UI, area/code, type/enhancement

#36 Teams: Added Traitor syncing
  code/gamemode/Game.ConVars.cs
  code/gamemode/Game.Util.cs
  code/gamemode/Game.cs
  code/player/TTTPlayer.Commands.cs
  code/player/TTTPlayer.RPCs.cs
  code/player/TTTPlayer.Roles.cs
  code/player/TTTPlayer.cs
  code/roles/InnocentRole.cs
  code/roles/NoneRole.cs
  code/roles/TTTRole.cs
  code/roles/TraitorRole.cs
  code/rounds/InProgressRound.cs
  code/teams/TTTTeam.cs
  code/ui/Nameplate.cs
  code/ui/Nameplate.scss
  code/ui/PlayerInfo.cs
  code/ui/PostRoundMenu.cs
  code/ui/QuickShop.cs
  code/ui/QuickShop.scss
  code/ui/ScoreboardEntry.cs
  ui/weapons/ttt_pistol.png
  ui/weapons/ttt_shotgun.png
  ui/weapons/ttt_smg.png
Labels: area/code, type/enhancement

#37 Fixes: Several game bugs
  code/gamemode/Game.cs
  code/items/weapons/Pistol.cs
  code/items/weapons/SMG.cs
  code/items/weapons/Shotgun.cs
  code/player/Inventory.cs
  code/player/TTTPlayer.cs
  code/rounds/BaseRound.cs
  code/rounds/InProgressRound.cs
  code/ui/GameTimer.cs
  code/ui/GameTimer.scss
  code/ui/QuickShop.cs
  code/ui/QuickShop.scss
  code/ui/WeaponSelection.cs
Labels: area/code, type/bug

#39 Shop: Restricted access to traitors
  code/items/weapons/TTTWeapon.cs
  code/player/TTTPlayer.Shop.cs
  code/player/TTTPlayer.cs
  code/roles/TTTRole.cs
  code/roles/TraitorRole.cs
  code/ui/QuickShop.cs
Labels: area/code

#41 Game: Several fixes
  code/gamemode/Game.cs
  code/items/weapons/AmmoType.cs
  code/items/weapons/Knife.cs
  code/items/weapons/Pistol.cs
  code/items/weapons/SMG.cs
  code/items/weapons/Shotgun.cs
  code/items/weapons/TTTWeapon.cs
  code/player/TTTPlayer.Status.cs
  code/player/TTTPlayer.cs
  code/rounds/InProgressRound.cs
  code/rounds/PreRound.cs
  code/rounds/WaitingRound.cs
Labels: area/code, type/enhancement

#40 Meta: Change editorconfig, update codebase
  .editorconfig
  code/gamemode/Game.cs
  code/items/equipments/TTTEquipment.cs
  code/items/weapons/TTTWeapon.cs
  code/items/weapons/ViewModel.cs
  code/items/weapons/WeaponFunctions.cs
  code/player/PlayerCorpse.cs
  code/player/TTTPlayer.Clothes.cs
  code/player/TTTPlayer.Confirmation.cs
  code/player/TTTPlayer.FallDamage.cs
  code/player/TTTPlayer.Status.cs
  code/player/TTTPlayer.cs
  code/player/camera/SpectateCamera.cs
  code/roles/TTTRole.cs
  code/rounds/BaseRound.cs
  code/rounds/InProgressRound.cs
  code/rounds/PreRound.cs
  code/rounds/WaitingRound.cs
  code/teams/TTTTeam.cs
  code/ui/Crosshair.cs
  code/ui/GameTimer.cs
  code/ui/Hud.cs
  code/ui/InfoFeedEntry.cs
  code/ui/InspectMenu.cs
  code/ui/Nameplate.cs
  code/ui/PlayerInfo.cs
  code/ui/PostRoundMenu.cs
  code/ui/QuickShop.cs
  code/ui/Scoreboard.cs
  code/ui/ScoreboardEntry.cs
  code/ui/WeaponSelection.cs
Labels: area/meta

#42 UI polish
  code/player/TTTPlayer.RPCs.cs
  code/ui/GameTimer.scss
  code/ui/InfoFeed.scss
  code/ui/InspectMenu.scss
  code/ui/Nameplate.cs
  code/ui/Nameplate.scss
  code/ui/PlayerInfo.scss
  code/ui/PostRoundMenu.scss
  code/ui/QuickShop.cs
  code/ui/QuickShop.scss
  code/ui/Scoreboard.scss
  code/ui/WeaponSelection.scss
Labels: area/UI, type/enhancement

#44 Fixed bug with Facepunch/sbox-issues#376 (custom LibraryAttributes)
  code/items/weapons/Knife.cs
  code/items/weapons/Pistol.cs
  code/items/weapons/SMG.cs
  code/items/weapons/Shotgun.cs
  code/items/weapons/TTTWeapon.cs
Labels: type/bug

#48 Hud: Delete huds on death
  code/ui/Hud.cs
  code/ui/InspectMenu.cs
Labels: area/UI, type/enhancement

#49 Game: Fix post round deaths, allow post round deaths
  code/player/TTTPlayer.Status.cs
  code/rounds/BaseRound.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
Labels: area/code, type/enhancement

#50 Fix: (Task) error handling, Hotloading issue with `NetworkedComponent`
  code/gamemode/Game.cs
  code/gamemode/Karma.cs
  code/items/weapons/TTTWeapon.cs
  code/player/PlayerCorpse.cs
  code/player/TTTPlayer.Roles.cs
  code/player/TTTPlayer.cs
  code/rounds/PostRound.cs
  code/ui/GameTimer.cs
  code/ui/Scoreboard.cs
Labels: area/code, type/enhancement

#53 Meta: Setup dotnet linting CI (with GH annotations)
  .editorconfig
  .github/workflows/dotnet.yml
  code/gamemode/Game.Util.cs
  code/gamemode/Game.cs
  code/items/equipments/TTTEquipment.cs
  code/items/weapons/AmmoType.cs
  code/items/weapons/Knife.cs
  code/items/weapons/Pistol.cs
  code/items/weapons/SMG.cs
  code/items/weapons/Shotgun.cs
  code/items/weapons/TTTWeapon.cs
  code/items/weapons/ViewModel.cs
  code/items/weapons/WeaponFunctions.cs
  code/player/Inventory.cs
  code/player/PlayerCorpse.cs
  code/player/TTTPlayer.Ammo.cs
  code/player/TTTPlayer.Clothes.cs
  code/player/TTTPlayer.Commands.cs
  code/player/TTTPlayer.Confirmation.cs
  code/player/TTTPlayer.FallDamage.cs
  code/player/TTTPlayer.RPCs.cs
  code/player/TTTPlayer.Roles.cs
  code/player/TTTPlayer.Status.cs
  code/player/TTTPlayer.cs
  code/player/camera/SpectateCamera.cs
  code/roles/TTTRole.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
  code/rounds/PreRound.cs
  code/ui/Crosshair.cs
  code/ui/InfoFeedEntry.cs
  code/ui/InspectMenu.cs
  code/ui/Nameplate.cs
  code/ui/QuickShop.cs
  code/ui/Scoreboard.cs
  code/ui/ScoreboardEntry.cs
  code/ui/WeaponSelection.cs
  tttreborn-ci.csproj
Labels: area/meta

#56 Meta: Allow CI linting to run without .csproj
  .github/workflows/dotnet.yml
  tttreborn-ci.csproj
Labels: area/meta

#58 Add scoreboard entry bgs
  code/ui/Scoreboard.scss
Labels: area/UI

#55 `AddEvent` -> `AddEventListener`
  code/ui/QuickShop.cs
Labels: area/meta

#71 Scoreboard: Added `MIA` group
  code/player/TTTPlayer.Confirmation.cs
  code/player/TTTPlayer.RPCs.cs
  code/player/TTTPlayer.Roles.cs
  code/player/TTTPlayer.cs
  code/roles/TTTRole.cs
  code/roles/TraitorRole.cs
  code/ui/Hud.cs
  code/ui/Scoreboard.cs
  code/ui/Scoreboard.scss
  code/ui/ScoreboardEntry.cs
Labels: area/UI, type/enhancement

#74 Cmds: Added permissions and validity checks
  code/player/TTTPlayer.Commands.cs
Labels: area/code

#76 Scoreboard: Fixed MIA state reset
  code/player/TTTPlayer.cs
Labels: area/code, type/bug

#54 Game: Add spectator & alive chat/voice
  code/gamemode/Game.Util.cs
  code/gamemode/Game.cs
  code/ui/ChatBox.cs
  code/ui/ChatBox.scss
  code/ui/ChatEntry.cs
Labels: area/code

#78 Change ref. https://github.com/Facepunch/sbox-issues/discussions/374
  .addon
  .gitignore
Labels: area/meta, type/enhancement

#77 Meta: Adjust import directives code style
  .editorconfig
  code/gamemode/Game.Util.cs
  code/gamemode/Game.cs
  code/items/equipments/TTTEquipment.cs
  code/items/weapons/TTTWeapon.cs
  code/items/weapons/ViewModel.cs
  code/items/weapons/WeaponFunctions.cs
  code/player/Inventory.cs
  code/player/TTTPlayer.Ammo.cs
  code/player/TTTPlayer.Clothes.cs
  code/player/TTTPlayer.Commands.cs
  code/player/TTTPlayer.FallDamage.cs
  code/player/TTTPlayer.RPCs.cs
  code/player/TTTPlayer.Roles.cs
  code/player/TTTPlayer.Status.cs
  code/player/TTTPlayer.cs
  code/player/camera/SpectateCamera.cs
  code/roles/TTTRole.cs
  code/rounds/BaseRound.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
  code/rounds/PreRound.cs
  code/rounds/WaitingRound.cs
  code/teams/TTTTeam.cs
  code/ui/Crosshair.cs
  code/ui/GameTimer.cs
  code/ui/InfoFeedEntry.cs
  code/ui/InspectMenu.cs
  code/ui/QuickShop.cs
  code/ui/Scoreboard.cs
  code/ui/WeaponSelection.cs
Labels: area/meta

#57 Meta: Add contributing guidelines and issue template
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  CONTRIBUTING.md
Labels: area/meta

#45 Weapon: Added MagnetoStick
  code/items/weapons/MagnetoStick.cs
  code/items/weapons/TTTWeapon.cs
  code/player/Inventory.cs
  code/player/PlayerCorpse.cs
  code/player/TTTPlayer.cs
  code/rounds/InProgressRound.cs
  code/ui/ChatBox.cs
  particles/rope.vpcf
  particles/rope.vpcf_c
Labels: area/code

#81 Cmd: Fixed `kill` cmd and added default `TTTTeam` `Nones`
  code/player/TTTPlayer.Roles.cs
Labels: type/bug, type/enhancement

#86 Hud: Rework hud, add hot reload to hud
  code/player/TTTPlayer.RPCs.cs
  code/ui/Hud.cs
Labels: area/code, type/enhancement

#87 UI polish #2
  code/ui/PlayerInfo.scss
  code/ui/Scoreboard.scss
  code/ui/WeaponSelection.scss
Labels: area/UI

#79 Rounds: Fixed that `WaitingRound` never triggered after a round started
  code/gamemode/Game.Util.cs
  code/gamemode/Game.cs
  code/rounds/InProgressRound.cs
  code/rounds/PostRound.cs
  code/rounds/PreRound.cs
  code/rounds/WaitingRound.cs
Labels: area/code, type/bug

#88 Bug: inspecting menu showing preround
  code/player/TTTPlayer.cs
Labels: area/code, type/bug
